version: "3.7"

services:
  database:
    container_name: "scheduler-database"
    image: mysql:latest
    tty: true
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped
    environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}  
    env_file:
        - .env
    ports:
        - 3306:3306
    expose:
        - 3306
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "scheduler-database-local:/var/lib/mysql"
    networks:
        - scheduler-network
#   elasticsearch:

volumes: 
    scheduler-database-local:
        driver: local

networks:
  scheduler-network:
    driver: bridge
